describe ("ModCloth", () => {      
    it("Going to Modcloth", () => {
      cy.visit('https://modcloth.com')
      cy.get('.glClose')
        .click()   
    })
  
    it.skip("#1 Going through search bar", () => {
      cy.get('.search-menu-item')
        .click()
      cy.get('#nogin-search-app > div > form > input')
        .type("Gift Card")
      cy.get('section > ul')
        .contains('Modcloth Gift Card')
        .click()
    })
  
    it(" #2 Going through footer", () => {
      cy.wait(2000)
      cy.get('.nav-link-gift-cards > .nav-link')
        .click()
    })
  
    it("#3 Validating the gift cards amount/cost", () => {
      cy.wait(4000)  
      cy.get('.changeShipping')
        .click()
      cy.get('select[id="gle_selectedCountry"]')
        .select('US')
      cy.get('.glSaveBtn')
        .click()
      cy.url()
        .should('contain', '/products/modcloth-gift-card')
      cy.contains('Modcloth Gift Card')
        .should('exist')
      cy.get('h1')
        .should('contain','Modcloth Gift Card')   
      cy.get('.my-5 .grid')
        .should('contain', '$10.00') 
      cy.get('.grid > :nth-child(2) > div > span')
        .should('contain', '$25.00')
      cy.get('.grid > :nth-child(3) > div > span')
        .should('contain', '$50.00')
      cy.get('.grid > :nth-child(4) > div > span')
        .should('contain', '$100.00')
    })
  
    it("#4 Adding one gift card to cart", () => {  
      cy.wait(1000)
      cy.get('.grid > :nth-child(2) > div > span') // $25.00
        .click()
      cy.get('.mb-4 > .btn')
        .click()
      cy.wait(3000)
      cy.get('.cc-allow') // Cookies
        .click()
      cy.contains('Your Shopping Bag')
        .should('exist') 
      cy.get('.cart-footer > .py-3')
        .click()
    })
  
    it("#6 Checkout, Contact Information", () => { 
      cy.wait(6000)
      cy.get('.changeShipping')
        .click()
      cy.get('select[id="gle_selectedCountry"]')
        .select('US')
      cy.get('.glSaveBtn')
        .click()  
      cy.wait(6000)
      cy.url()
        .should('contain', '/checkouts')
      cy.contains('Contact information')
        .should('exist')
      cy.get('#checkout_billing_address_country')
        .then( $country => {
          $country.val("United States")
        })
        .parent()
        .trigger("change")
      cy.get('#checkout_billing_address_province')
        .select('CA')
      cy.get('#checkout_email')
        .type('aida.barajas@michelada.io')
      cy.get('[id="checkout_buyer_accepts_marketing"]')
        .uncheck()
      cy.get('#checkout_billing_address_first_name')
        .type('Aida')
      cy.get('#checkout_billing_address_last_name')
        .type('Barajas')
      cy.get('#checkout_billing_address_address1')
        .type('20131 Runnymede Street')
      cy.get('#checkout_billing_address_city')
        .type('Los Angeles')
      cy.get('#checkout_billing_address_zip')
        .type(91306)
      cy.get('#checkout_billing_address_phone')
        .type(3121457730)
      cy.wait(9000)
      cy.get('#continue_button')
        .click()
    })
    
    it("#6 Checkout Payment info", () => {
      cy.get('.card-fields-iframe').then($iframe => {
        const $body = $iframe.contents().find('body')
      cy.wrap($body)
        .find('input#number')
        .eq(0)
        .type('4242424242424242')
      cy.wrap($body)
        .find('input#name')
        .eq(1)
        .type('Aida Barajas')
      cy.wrap($body)
        .find('input#expiry')
        .eq(2)
        .type('05/25')
      cy.wrap($body)
        .find('input#verification_value')
        .eq(3)
        .type('987')
        })
      })

    })
