describe ("ModCloth", () => {      
  it("Going to Modcloth", () => {
    cy.visit('https://modcloth.com')
    cy.get('.glClose')
      .click()   
  })

  it("#1 Going through search bar", () => {
    cy.get('#icon_search')
      .click()
    cy.get('#nogin-search-app > div > form > input')
      .type("Gift Card")
    cy.get('section > ul')
      .contains('Modcloth Gift Card')
      .click()
  })

  it.skip("#2 Going through footer", () => {
    cy.wait(2000)
    cy.get('.nav-link-gift-cards > .nav-link')
      .click()
    cy.contains('Home / Modcloth Gift Card')
      .should('exist')   
  })

  it("#3 Validating the gift cards amount/cost", () => {
    cy.get('.changeShipping')
      .click()
    cy.get('select[id="gle_selectedCountry"]')
      .select('US')
    cy.get('.glSaveBtn')
      .click()
    cy.url()
      .should('contain', '/products/modcloth-gift-card')
    cy.contains('Modcloth Gift Card')
      .should('exist')
    cy.get('h1')
      .should('contain','Modcloth Gift Card')
      .get('.my-5 .grid')
      .should('contain', '$10.00') 
    cy.get('.grid > :nth-child(2) > div > span')
      .should('contain', '$25.00')
    cy.get('.grid > :nth-child(3) > div > span')
      .should('contain', '$50.00')
    cy.get('.grid > :nth-child(4) > div > span')
      .should('contain', '$100.00')
  })

  it("#5 Adding several gift cards to cart", () => {
    cy.get('.grid > :nth-child(4) > div > span')//2 de $100
      .click()
    cy.get('select[class="text-input"]')
      .select('2')
    cy.get('.mb-4 > .btn')
      .click()
    cy.wait(4000)
    cy.get('.flex > .cursor-pointer')
      .click()    
    cy.get('.grid > :nth-child(3) > div > span')//3 de $50
      .click()
    cy.get('select[class="text-input"]')
      .select('3')
    cy.get('.mb-4 > .btn')
      .click()
    cy.wait(4000)
    cy.get('.flex > .cursor-pointer')
      .click()
    cy.get('.grid > :nth-child(2) > div > span') //5 de $25
      .click()
    cy.get('select[class="text-input"]')
      .select('5')
    cy.get('.mb-4 > .btn')
      .click()
    cy.wait(4000)
    cy.get('.flex > .cursor-pointer')
      .click()
    cy.get('.grid > :nth-child(1) > div > span') //10 de $10
      .click()
    cy.get('select[class="text-input"]')
      .select('10')
    cy.get('.mb-4 > .btn')
      .click()
    cy.wait(4000)
    cy.get('.cc-allow')
      .click()
    cy.wait(2000)
    cy.contains('Your Shopping Bag')
      .should('exist') 
    cy.get('.cart-footer > .py-3')//Going to checkout
      .click()
  })

  it("#6 Checkout, Contact Info", () => { 
    cy.wait(6000)
    cy.get('.changeShipping')
      .click()
    cy.get('select[id="gle_selectedCountry"]')
      .select('US')
    cy.get('.glSaveBtn')
      .click()  
    cy.wait(6000)
    cy.url()
      .should('contain', '/checkouts')
    cy.contains('Contact information')
      .should('exist')
    cy.get('#checkout_billing_address_country')
      .then( $country => {
        $country.val("United States")
      })
      .parent()
      .trigger("change")
    cy.get('#checkout_billing_address_province')
      .select('CA')
    cy.get('#checkout_email')
      .type('aida.barajas@michelada.io')
    cy.get('[id="checkout_buyer_accepts_marketing"]')
      .uncheck()
    cy.get('#checkout_billing_address_first_name')
      .type('Aida')
    cy.get('#checkout_billing_address_last_name')
      .type('Barajas')
    cy.get('#checkout_billing_address_address1')
      .type('20131 Runnymede Street')
    cy.get('#checkout_billing_address_city')
      .type('Los Angeles')
    cy.get('#checkout_billing_address_zip')
      .type(91306)
    cy.get('#checkout_billing_address_phone')
      .type(3121457730)
    cy.wait(6000)
    cy.get('#continue_button')
      .click()
  })

  it("#6 Checkout, Payment info", () => {
    cy.get('.card-fields-iframe').then($iframe => {
      const $body = $iframe.contents().find('body')
    cy.wrap($body)
      .find('input#number')
      .eq(0)
      .type('4242424242424242')
    cy.wrap($body)
      .find('input#name')
      .eq(1)
      .type('Aida Barajas')
    cy.wrap($body)
      .find('input#expiry')
      .eq(2)
      .type('05/25')
    cy.wrap($body)
      .find('input#verification_value')
      .eq(3)
      .type('987')
      })
    })
  })