describe ("ModCloth", () => {      

    it("Adding one $100.00 gift card to cart", () => {  
      cy.visit('http://modcloth.com/products/modcloth-gift-card')
      cy.wait(4000)
      cy.get('.changeShipping')
        .click()
      cy.get('select[id="gle_selectedCountry"]')
        .select('US')
      cy.get('.glSaveBtn')
        .click()
      cy.wait(4000)
      cy.wait(1000)
      cy.get('.grid > :nth-child(4) > div > span')
        .click()
      cy.get('.mb-4 > .btn')
        .click()
      cy.wait(2000)
      cy.get('.cc-allow')
        .click()
      cy.contains('Your Shopping Bag')
        .should('exist') 
      cy.get('.cart-footer > .py-3')
        .click()
    })
  
    it("Checkout", () => { 
      cy.wait(6000)
    //   cy.get('.changeShipping')
    //     .click()
    //   cy.get('select[id="gle_selectedCountry"]')
    //     .select('US')
    //   cy.get('.glSaveBtn')
    //     .click()  
      cy.wait(1000)
      cy.contains('Contact information')
        .should('exist')
        // cy.get('#checkout_billing_address_province')
        // .select('CA')
        cy.get('#checkout_email')
        .type('aida.barajas@michelada.io')
        cy.get('[id="checkout_buyer_accepts_marketing"]')
        .uncheck()
        cy.get('#checkout_billing_address_first_name')
        .type('Aida')
        cy.get('#checkout_billing_address_last_name')
        .type('Barajas')
        cy.get('#checkout_billing_address_country')
          .select('United States')
        cy.get('#checkout_billing_address_address1')
        .type('20131 Runnymede Street')
      cy.get('#checkout_billing_address_city')
        .type('Los Angeles')
      cy.get('#checkout_billing_address_zip')
        .type(91306)
      cy.get('#checkout_billing_address_phone')
        .type(3121457730)
      cy.wait(7000)
      cy.get('#continue_button')
        .click()
    })
  })
    
    