describe ("ModCloth", () => {      
  it("Going to Modcloth", () => {
    cy.visit('https://modcloth.com')
    cy.get('.glClose')
      .click()   
  })

  it.skip("Going through search bar", () => {
    cy.get('.search-menu-item')
      .click()
    cy.get('#nogin-search-app > div > form > input')
      .type("Gift Card")
    cy.get('section > ul')
      .contains('Modcloth Gift Card')
      .click()
  })

  it("Going through footer", () => {
    cy.wait(2000)
    cy.get('.nav-link-gift-cards > .nav-link')
      .click()
    cy.contains('Home / Modcloth Gift Card')
      .should('exist')   
  })

  it("Validating the gift cards amount/cost", () => {
    // cy.visit('https://modcloth.com/products/modcloth-gift-card?_ab=0&_fd=0&_sc=1&preview_theme_id=129702756523')
    cy.wait(6000)
    // cy.get('#ge_ss1280_0')
    //   .click()
    // cy.get('.glClose')
    //   .click()   
    cy.get('.changeShipping')
      .click()
    cy.get('select[id="gle_selectedCountry"]')
      .select('US')
    cy.get('.glSaveBtn')
      .click()
    cy.url()
      .should('contain', '/products/modcloth-gift-card')
    cy.contains('Modcloth Gift Card')
      .should('exist')
    cy.get('h1')
      .should('contain','Modcloth Gift Card')   
    cy.get('.my-5 > .grid')
      .should('contain', '$10.00') 
    cy.get('.grid > :nth-child(2) > div > span')
      .should('contain', '$25.00')
    cy.get('.grid > :nth-child(3) > div > span')
      .should('contain', '$50.00')
    cy.get('.grid > :nth-child(4) > div > span')
      .should('contain', '$100.00')
  })

  it("Adding one gift card to cart", () => {
    // cy.wait(7000)  //descomentar si se skipea prueba anterior
    // cy.get('.cc-allow')
    //   .click()
    // cy.get('.changeShipping')
    //   .click()
    // cy.get('select[id="gle_selectedCountry"]')
    //   .select('US')
    // cy.get('.glSaveBtn')
    //   .click()

    cy.wait(1000)
    // cy.get('.grid > :nth-child(4) > div > span')
    //   .click()
    cy.get('.mb-4 > .btn')
      .click()
    cy.wait(2000)
    cy.get('.cc-allow')
      .click()
    cy.contains('Your Shopping Bag')
      .should('exist') 
    
    cy.get('.cart-footer > .py-3')//Going to checkout
      .click({})
  })

  it("Checkout", () => { 
    cy.wait(6000)
    cy.get('.changeShipping')
      .click()
    cy.get('select[id="gle_selectedCountry"]')
      .select('US')
    cy.get('.glSaveBtn')
      .click()  
    cy.wait(6000)
    cy.contains('Contact information')
      .should('exist')

    // cy.get('.glClose')
    //   .click()

    cy.get('#checkout_billing_address_country')
      .then( $country => {
        $country.val("United States")
      })
      .parent()
      .trigger("change")
    cy.get('#checkout_billing_address_province')
      .select('CA')
    cy.get('#checkout_email')
      .type('aida.barajas@michelada.io')
    cy.get('[id="checkout_buyer_accepts_marketing"]')
      .uncheck()
    cy.get('#checkout_billing_address_first_name')
      .type('Aida')
    cy.get('#checkout_billing_address_last_name')
      .type('Barajas')
    cy.get('#checkout_billing_address_address1')
      .type('20131 Runnymede Street')
    cy.get('#checkout_billing_address_city')
      .type('Los Angeles')
    cy.get('#checkout_billing_address_zip')
      .type(91306)
    cy.get('#checkout_billing_address_phone')
      .type(3121457730)
    cy.wait(9000)

    // cy.contains('Continue to payment')
    //   .should('exist')
    //   .click()
    cy.get('#continue_button')
      .click()
  })

  it("Payment info", () => {
    cy.wait(1000)
    cy.get('input[name="number"]')
      .type('5201099865790543')
    cy.get('#card-fields-name-gxs2kquftef00000-scope-modcloth\.com')
      .type('Aida Alejandra Barajas Sanchez')
    cy.get('#card-fields-expiry-loem3fjye1000000-scope-modcloth\.com')
      .type('04/25')
    cy.get('#card-fields-verification_value-maxnkiydy6000000-scope-modcloth\.com')
      .type('888')
    cy.get('.step__footer > .shown-if-js')
      .click()
  })


})
  
  